[tool.mypy]
python_version = "3.10"
warn_return_any = false
warn_unused_configs = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
warn_redundant_casts = false
warn_unused_ignores = false
warn_no_return = false
warn_unreachable = false
ignore_missing_imports = true
follow_imports = "skip"
follow_imports_for_stubs = true
plugins = ["mypy_django_plugin.main"]
disable_error_code = ["var-annotated", "annotation-unchecked", "misc"]

[[tool.mypy.overrides]]
module = [
    "django.*",
    "channels.*",
    "rest_framework.*",
    "rest_framework_simplejwt.*",
    "trips.*",
    "taxi.*",
    "asgiref.*",
    "channels_redis.*",
]
ignore_missing_imports = true
disable_error_code = ["var-annotated", "annotation-unchecked", "misc"]
